### ISSUE TITLE
How we should present it?

### ISSUE THREAD

**Issue by LauAvinyo** [jlgelpi/BioPhysics2017-18#1]
Hi, 

I am starting to work on the script, so I would like to now how we have to share it with you.
Should we create our own repo, with its readme and so on, and then share a link to you?

Thanks,
Laura

**Comment by jlgelpi** [comment]
Hi, yes, you shoud use your own github account to deposit the script(s).  
In fact this will be the procedure from now on also in other subjects, so create a specific repo/project for Biophysics.
In the ESCI campus it will be a place to upload the report on the results, and the address to the repo. 
Best

Josep Ll.

**Comment by LauAvinyo** [comment]
Another question, 
Which formula should we use for calculate VdW forces. 
I have found more than one on the exercises..., and actually they are only for same atom...

Thanks, 
Laura

**Comment by LauAvinyo** [comment]
It is me again.
I am computing VDW, and i can not find the parameters of some types of atoms.
Actually, which is the difference between, for instance, HB1 and  H?
And what should we use?
For electrostatics I have use the HB1 column, is it correct?

**Comment by jlgelpi** [comment]
The correspondence between atom names and types is in the residue library, and the corresponding vdw parameters (for the atom types) in the vdwprm file. The process should be residue+atom names -> atom type (and also charge) -> vdw params. Atom types are less than possible atom names, as several atoms belong to the same type. HB1 is normaly a hydrogen in a beta carbon, so it is normally of type "H" (hydrophobic hydrogen).  Yu can have problems with atoms in the N-term or C-Term aminoacids that has a different set of atoms, these are "different" residue names in the library (MTN instead of MET). 
In the case of Ala scanning you need to replace aminoacids by Ala, that means remove all atom in the side chain but the CB and eventually HBx. However since the complete Ala has 3 H the third H must be invented (can be taken form the CG atom when present, but the geometry is wrong). In this case it is ok use only CB without hidrogens that have the charge of CB+HB1+HB2+HB3 and just the vdw of a single C. A more accurate way (if you like) would be to define a CB* atom that recovers the vdw and charge of the complete methyl group, and use it a Ala side chain.

**Comment by LauAvinyo** [comment]
I have some questions:
1. When I am coumputing Residues interactions if I use all the Pairwase atom interactions I get the same values as energies0 but if I use only the atoms that actually interact the values are much higer. eg. VAL LYS	(-4.7478438909969611, -2.304194915054107)	(21.444931717773684, 0.068822868281283783)
I am quite confuse, because the functions and the data I use to get these values are the same. (It would be cool if you could check the code anyway). Then for the plot Stability vs number of atoms involved what should I do? Because in exercise b, i am only taking into account the ones that really interact!
2. When you say: most stable interaction is actually higher absolute value, right?
3. Why in some classes sigma of vdw is multiply by 0.52 and in other is not? And why this scaling factor?
4. The ALA scanning: How we can get AAG? Because I understand that AG =  AH + TAS. Where in physiologic conditions AH is U. Then we could make the difference of the values of the residues interactions and get AH. Is this right? But what shall we do with entropy? We assume that mutant and entropy and wt has the same entropy? If so, the plot is actually: in y: (elec + vdw)original - (elec+vdw)mutant ; in x the residue index?
5. More ALA scanning: My idea was to use already an alanine (indeed I use the residue 28) instead of mutating the residue. The problem is that  I use the alpha carbon coordinate for all ALA atoms. Is this correct? Or I should use a better method?

**Comment by jlgelpi** [comment]
Hi, 
1: The results are correct. The reason of the difference is that electrostatics is modelled using partial charges centered in the atoms. Although we use the closest atoms to define the interactions, the sourrounding atoms are also contributing to the energy. For instance in the case of CO - NH interaction, both groups are neutral (as net charge), however they have electrostatic interaction energy since the charge is not equally distributed. Negative charge concentrates in O and N, and positive in C and H (look to the library to see the actual  values). This gives a distribution C+ O- H+ N- that is the actual hydrogen bond.  Using only O and N (... O- ... N-)  you get a positive value, since would represent a repulsive interaction that is not real. The correct value, giving a favourable interaction, requires the contribution of C and H charges. The most correct way of solving the exercise is using the interaction between the chemical groups involved, however this is much more complex that using the complete residues and would give a similar result. This is less evident for the vdw, however, as you see the difference is also significant. Use the residue-residue energies for all energy plots. For the classification (Ex 2) the contact residues are fine.
2: Correct. the "most negative" 
3: Sigma*0.5612 gives the Rmin. Rmin is used in the alternated vdw formula, and also to define surfaces and volumes. You can find the details in Prob. 2.1.8. 
4: Indeed, the usual way we do this kind of analysis is considering that entropy does not change. This aproximation is not perfect but good enough in most cases. So, you should get only the difference in H, i.e. the differences of the energies that you are calculating. 
5: No, in this way if I am understanding correctly you are doing more a mutation to GLY that has no side chain. To use an existing ALA you should superimpose it into the actual residue that you are mutating, what is not easy, otherwise you loose the ALA geometry. A much easier method is delete all atoms in the side chain except the CB, and replace charges and atom types (backbone and CB) to those of ALA residue. In this way you do not need to invent the coordinates, you are using those of the original atoms, but the "new" residue will behave as Ala. To avoid the problem of the 3 H needed for Ala CB, simply use the whole charge of CH3 for the CB and delete also the Hs. Ideally you should also increase the vdw sigma of the CB to include them, but this difference is not much significant. Also you would have a problem  with Gly->Ala mutations, however as these have no side chain contacts, the difference is minimal.

**Comment by LauAvinyo** [comment]
Thank you very much for your answer!
5, Yes, I understand. I will try to do it this way. 
But, actually what I am doing is the following. Lets say that I want to compute the interaction of residue1 and residue2 with residue two mutated.
I get the atoms for a residue 1.
I get the atoms for one ALA.
I compute the energies using as always but with the only difference that the all the distances are computed (atom_from_residue1 - carbon_alpha_residue2).

**Comment by jlgelpi** [comment]
Ok, the problem is that you are using only one atom for computing the distances, so the values are not correct. For instance if you are analyzing a main-main interaction, these should not change much mutating to Ala as Ala has also the same main chain atoms as the original residue. However using only the CA the distances change and hence the energies will change. 
In fact, the calculation can be even easier: using the same double loop you use for getting the normal residue1 - residue 2 energies, simply skip atoms in 2 that do not exist in an Ala residue and use Ala charge distribution In this way you keep the original coordinates and distances.

**Comment by LauAvinyo** [comment]
But then I still have the problem with Gly and the 3 hydrogens of Ala, right?
There are some values for CH3 charge in the aaLib for ACE and NME. Should we use one of them? Or I do not take this into account? (I have not found any value in Internet...)

**Comment by jlgelpi** [comment]
Yes. 
Data for CH3 group of Ala is in the library (ALA CB, ALA HB...), ACE and NME are not valid as they are main chain atoms (although the difference would be small).
For all aminoacids except Gly you have already a CB atom to get the coordinates, the easiest aprox is to give to that atom the charge of  a complete ALA CH3 (i.e. CB + HB1 + HB2 + HB3 = - 0.0016). Since the group is almost neutral with a very small dipol, the aproximation is correct. For the Vdw use simply the CB values (the correct aproximation here would be using a sligthly larger CB atom to include the vdw effects of the Hs, but this would be extra work). 
In the case of Gly, the correct procedure would be to model a new CB atom, this can be done using the appropriate HA atom of the Gly and extending the bond to the right distance, however, this is too complicated for this exercise. You may use your previous aproach (the CA coordinates).
Summary:
For GLY->ALA: Use the actual coordinates for backbone atoms. Use CA (or HA) coordinates for new CB.
For ALA->ALA: obviously no need to do anything
For Other->ALA:
Delete all non-Ala atoms from the side chain.
Delete HB atoms
Use ALA charges and Vdw for backbone
Use complete charge of ALA side (-0.0016) and normal C vdw for CB

**Comment by LauAvinyo** [comment]
Hello, again!

But I think is the last one!
I am quite confuse with the units. In the data there is no units and I am not able to figure them out.
I guess that the hint is the 332.6, I know that k = 8.98E9 Nm² / C². I do not though the C, but I have try to change Nm (joules) to KCal and then m to Angtroms, but as you see I've failed. And If I change C² to eV² it is _quite_ worst. 
And for VdW , my supposition is that the energies maybe kJ or kCal, but I don't see any hint to choose between them.
Finally, this energy units are normalized by number mols? I mean, could be that the final units is KJ/mol or KCal/mol? 

And looking for the exam. Normally the energy in which units we work? In your solutions everything is in kcal, but since know we did everything in Joules. 

Thanks a lot,

**Comment by jlgelpi** [comment]
Hi, 
The short answer is that with the 332.16, charges in 'e' and distance in Angstr. the energy comes in kcal/mol.
Explanation: From the k: Nm goes to J, Then charge units: C should go to e (electron) units, use 1.602e-19 C/e, the remaining m  to Angs. A = 1e-10m. This will give J.A/e2. 1cal = 4.18 J, 1kcal=1000cal, and finally this is 1 atom interaction, it should go to  1 mol = 6.023e23 atoms. All together should give 332.16 kcal. A/e2. A bit tricky, so we tend to remember the magic 332.16 :-)
For Vdw,  energy units come from the Eps parameter which is normally in kcal/mol, although some forcefields prefer to use kJ/mol. Sigma should have the same unit as distance, normally Angs, although again some simulation programs like gromacs use nanometers. 
and yes all energies are /mol . 
Using KJ or Kcal is matter or history, there is an "official" preference, as J  is the "correct" unit for energy, but a lot of people (myself included) and programs use cal, and it is also the only option in experimental papers. It does not matter as long as the unit is indicated and we are aware of the difference.

I know this can be a mess, but every piece of software uses their own version of the units, normally following the personal preferences of the developer.  We should be aware of that and just keep track of what is used. In fact this could be even worse. Since unit conversions implies a lot of repetitive calculations that make programs less efficient, when optimizing code it is quite normal to "invent" units to avoid this conversions, only when presenting results the proper units are shown.
